// utils/synonyms.js
const synonyms = {
  // --- Programming Languages ---
  js: "javascript",
  javascript: "javascript",
  ts: "typescript",
  typescript: "typescript",
  py: "python",
  python: "python",
  csharp: "c#",
  "c#": "c#",
  cpp: "c++",
  "c++": "c++",
  java: "java",
  golang: "go",
  go: "go",
  ruby: "ruby",
  php: "php",
  swift: "swift",
  kotlin: "kotlin",
  rust: "rust",
  scala: "scala",

  // --- Web & Frontend ---
  reactjs: "react",
  react: "react",
  next: "next.js",
  "next.js": "next.js",
  angularjs: "angular",
  angular: "angular",
  vuejs: "vue",
  vue: "vue",
  svelte: "svelte",
  html: "html",
  css: "css",
  tailwind: "tailwindcss",
  bootstrap: "bootstrap",
  express: "express.js",
  expressjs: "express.js",
  jquery: "jquery",
  ajax: "ajax",

  // --- Backend & Frameworks ---
  node: "nodejs",
  nodejs: "nodejs",
  express: "express.js",
  "express.js": "express.js",
  springboot: "spring boot",
  spring: "spring boot",
  django: "django",
  flask: "flask",
  fastapi: "fastapi",
  laravel: "laravel",
  rails: "ruby on rails",
  "ruby on rails": "ruby on rails",
  dotnet: ".net",
  ".net": ".net",

  // --- Databases ---
  sql: "sql",
  mysql: "sql",
  postgres: "postgresql",
  postgresql: "postgresql",
  mariadb: "sql",
  sqlite: "sql",
  mongodb: "mongodb",
  cassandra: "cassandra",
  redis: "redis",
  firestore: "firebase",
  dynamodb: "dynamodb",
  neo4j: "neo4j",
  db: "database",
  database: "database",

  // --- Cloud & DevOps ---
  aws: "amazon web services",
  "amazon web services": "amazon web services",
  azure: "microsoft azure",
  gcp: "google cloud platform",
  "google cloud": "google cloud platform",
  docker: "docker",
  k8s: "kubernetes",
  kubernetes: "kubernetes",
  jenkins: "jenkins",
  github: "github",
  gitlab: "gitlab",
  bitbucket: "bitbucket",
  terraform: "terraform",
  ansible: "ansible",
  ci: "ci/cd",
  cd: "ci/cd",
  cicd: "ci/cd",

  // --- AI / ML / Data Science ---
  ml: "machine learning",
  "machine learning": "machine learning",
  ai: "artificial intelligence",
  "artificial intelligence": "artificial intelligence",
  nlp: "natural language processing",
  "natural language processing": "natural language processing",
  dl: "deep learning",
  "deep learning": "deep learning",
  cv: "computer vision",
  "computer vision": "computer vision",
  tensorflow: "tensorflow",
  pytorch: "pytorch",
  keras: "keras",
  sklearn: "scikit-learn",
  "scikit-learn": "scikit-learn",
  transformers: "huggingface transformers",
  huggingface: "huggingface transformers",
  spacy: "spacy",
  opencv: "opencv",
  llm: "large language model",
  "large language model": "large language model",
  gpt: "large language model",
  bert: "bert",
  roberta: "roberta",
  xgboost: "xgboost",
  lightgbm: "lightgbm",
  catboost: "catboost",
  pandas: "pandas",
  numpy: "numpy",
  matplotlib: "matplotlib",
  seaborn: "seaborn",
  jupyter: "jupyter notebook",
  "jupyter notebook": "jupyter notebook",

  // --- Tools & Misc ---
  linux: "linux",
  windows: "windows",
  macos: "macos",
  jira: "jira",
  confluence: "confluence",
  slack: "slack",
  vscode: "visual studio code",
  "visual studio code": "visual studio code",
  intellij: "intellij",
  eclipse: "eclipse",
  postman: "postman",
  figma: "figma",
  miro: "miro",

  amazon: "amazon web services",
  aws: "amazon web services",

  "firebase hosting": "firebase",
  "firebase authentication": "firebase",
  "firebase auth": "firebase",
  "firebase cloud functions": "firebase",
  "firebase functions": "firebase",
  "firebase storage": "firebase",
  "firebase cloud messaging": "firebase",
  fcm: "firebase",
  "firebase push notifications": "firebase",
  "firebase analytics": "firebase",
  "firebase crashlytics": "firebase",
  "firebase test lab": "firebase",
};

module.exports = { synonyms };
